name: Trigger GitLab CI/CD

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitLab Trigger API
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/trigger/pipeline \
            -F token=$GITLAB_TRIGGER_TOKEN \
            -F ref=main
        env:
          GITLAB_PROJECT_ID: 71855342
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
